### ISSUE TITLE
Add ability to create requirements that do not expect a source code implementation

### ISSUE THREAD

**Issue by lfvbarcus** [Luftfartsverket/reqstool-client#17]
## Summary

There will be some requirements that are not furfilled by the source code alone, there needs to be a way to say that the requirement does not require an source code implementation.

example: a requirement that is fulfilled by the platform it runs on and is not implemented in the source code.

We need to come up with a clever way of doing this. Until a solution is in place, a workaround could be to create a Java class `NoSourceImplementation.java` and annotate the requirements that would not need any real source code implementation there. This would work in the same way with Python of course.

**Comment by lfvbarcus** [comment]
This issue is quite difficult to get right, as it breaks a lot of the logic related to how we calculate statistics. 

First, let's check on how this feature is currently implemented. 

A requirement can be specified with or without the variable `implemented_in_src`. This variable is not marked as a required field in the schema file, and will default to True if not set explicitly

![image](/uploads/c90376eeef523b804f6a341d5c1b4bfc/image.png)


However, I'm not sure how we should count and visually present requirements that does not require an implementation. 

In the table generated by the status command, such a requirement (REQ_1337 in the image below) is marked green as it is completed in the sense that it should not have an implementation, and all tests are passed, but the Implementation is marked as 'Missing'

![image](/uploads/89ca9cf802323213eaf3b011716bee5d/image.png)

My question about this new feature is as follows: 

1. Is my assumption that A requirement that should not require an implementation, but is tested and all tests pass, should be counted as 'Implemented and Verified' correct?
2. What should the 'Implemented' column of the status table read for such a requirement? N/A? Skipped?

Could you guys provide me with some feedback on how we should address those questions?
@u30576 @u70565 @u70579 @u70650

**Comment by rlinhem** [comment]
1. yes, if the tests pass the requirement is verified. 
2. A 'N/A' mark in the Implementation column would work.

**Comment by lfvjimisola** [comment]
> 1. yes, if the tests pass the requirement is verified.
> 2. A 'N/A' mark in the Implementation column would work.

Agree.

I'm just not sure about `implemented_in_src`.

Also, what should we do if we find an implementation for a requirement that should not have one?

**Comment by lfvbarcus** [comment]
> > 1. yes, if the tests pass the requirement is verified.
> > 2. A 'N/A' mark in the Implementation column would work.
> 
> Agree.
> 
> I'm just not sure about `implemented_in_src`.
> 
> Also, what should we do if we find an implementation for a requirement that should not have one?

I'm also on the fence about the wording of the variable. I just went with one of your suggestions from a previous discussion. maybe `implementation_expected` is better?

I'm not sure how we should handle that scenario. Normally we just throw an error and log a message, but I'm open for suggestions.

**Comment by lfvbarcus** [comment]
I opened up a PR for this matter. We can continue the discussion there

@lfvjimisola @rlinhem

**Comment by rlinhem** [comment]
> Also, what should we do if we find an implementation for a requirement that should not have one?

If a requirement is marked to not have a implementation but there is an annotation with that requirement id in the code it's a user error. Throw a error and log it.
Either the requirement is erroneous marked or the code annotation is wrong. You can't have both anyway.

**Comment by lfvjimisola** [comment]
> > Also, what should we do if we find an implementation for a requirement that should not have one?
> 
> If a requirement is marked to not have a implementation but there is an annotation with that requirement id in the code it's a user error. Throw a error and log it. Either the requirement is erroneous marked or the code annotation is wrong. You can't have both anyway.

Just to confirm. We should stop the parsing?
