### ISSUE TITLE
Test report from pytest will not be read properly

### ISSUE THREAD

**Issue by lfvbarcus** [Luftfartsverket/reqstool-client#44]
During parsing, Reqstool finds the report.xml file generated from pytest, but it can't read the test case element(s) of the root node. 

See line 37 in test_data_generator.py

A sample xml file is provided [here](https://github.com/Luftfartsverket/reqstool-client/files/14611970/report.zip)

The report file could also be generated using the following:

```
hatch run test:pytest --cov=reqstool-client --cov-report=xml --cov-report=html -o junit_family=xunit2 --junitxml=dist/report.xml 
```

**Comment by lfvjimisola** [comment]
Is it possible to use junit_family=xunit1?

https://docs.pytest.org/en/7.1.x/deprecations.html#id22

**Comment by lfvbarcus** [comment]
This has been fixed [here](https://github.com/Luftfartsverket/reqstool-client/pull/54).
