### ISSUE TITLE
Implement fields to comment and mark a requirements/svc as no longer valid

### ISSUE THREAD

**Issue by lfvbarcus** [luftfartsverket/reqstool-client#46]
## Summary

Requirements evolve and sometimes a requirement isn't valid anymore but we shouldn't just remove it. There should be a way to mark it as non-valid and have space to explain why.

Some reason could be.

- clash or overlap with other requirement
- changed environment, something outside of the project change.
- new insights gained

Same goes for svcs.

## Proposal

* Introduce an optional field called `comment` on both requirements.yml and software_verification_cases.yml. The comment field could be used as a field to explain why a requirement/svc is no longer valid or to make other comments regarding the requirement/svc during the writing process. The comment field should not be parsed or validated when Reqstool is running.
* On both `requirements.yml` and `software_verification_cases.yml`, add a field called `lifecycle_state` that could have one of four states:
  * draft 
  * effective (default)
  * deprecated
  * obsolete

Actions to take:

- [ ] Update schema files for requirements.yml and software_verifications_yml
- [ ] Implement logic to read/check for new fields and set defaults
- [ ] Log if reqstool-client detects deprecated and/or obsolete requirements/svcs.

**Comment by lfvbarcus** [comment]
![image](https://github.com/luftfartsverket/reqstool-client/assets/142776362/c3f17d44-90ca-42ae-a878-644aa1ee357c)

**Comment by lfvjimisola** [comment]
> ![image](https://private-user-images.githubusercontent.com/142776362/338486130-c3f17d44-90ca-42ae-a878-644aa1ee357c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwOTI5ODgsIm5iZiI6MTcxODA5MjY4OCwicGF0aCI6Ii8xNDI3NzYzNjIvMzM4NDg2MTMwLWMzZjE3ZDQ0LTkwY2EtNDJhZS1hODc4LTY0NGFhMWVlMzU3Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMVQwNzU4MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYjNmZGYzY2Y3ODhhZjc4ZDk5OWRiMTY0NjFmMjhlZTdkYThjYTg3Y2EyMDhlNTRiYTUyNTBkNTVhNmQxYzk0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8WNQpdk311r54OuLAgeQH-EmnrTLXgGg54Go7UuFbM8)
> 
> @lfvjimisola @rlinhem @lfvmarcus could this work as an implementation of the required feature?

If lifecycle is missing then we default to lifecycle.state = effective?

**Comment by lfvbarcus** [comment]
> > ![image](https://private-user-images.githubusercontent.com/142776362/338486130-c3f17d44-90ca-42ae-a878-644aa1ee357c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwOTI5ODgsIm5iZiI6MTcxODA5MjY4OCwicGF0aCI6Ii8xNDI3NzYzNjIvMzM4NDg2MTMwLWMzZjE3ZDQ0LTkwY2EtNDJhZS1hODc4LTY0NGFhMWVlMzU3Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMVQwNzU4MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYjNmZGYzY2Y3ODhhZjc4ZDk5OWRiMTY0NjFmMjhlZTdkYThjYTg3Y2EyMDhlNTRiYTUyNTBkNTVhNmQxYzk0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8WNQpdk311r54OuLAgeQH-EmnrTLXgGg54Go7UuFbM8)
> > @lfvjimisola @rlinhem @lfvmarcus could this work as an implementation of the required feature?
> 
> If lifecycle is missing then we default to lifecycle.state = effective?

Yes, that's the idea. Also, comment should only be required if lifecycle.state == depricated or obsolete
